### ISSUE TITLE
Versioning, publishing crate

### ISSUE THREAD

**Issue by szg251** [mlabs-haskell/plutus-ledger-api-rust#20]
# Blocked by:
https://github.com/mlabs-haskell/lambda-buffers/issues/178

# TODO
- [x] bump version to v1
- [ ] configure CI to publish crates to crates.io
- [ ] if not to difficult, generate documentation to github pages (otherwise, using docs.rs is also sufficient)
- [ ] push a git tag
